title: 'Set Hallström'
description: >- # this means to ignore newlines until "baseurl:"
  The Digital CV of Set Hallstrom, a multi-disciplanry Artist, a Free Software
  advocate and Community Manager.

url: "https://set.hallstrom.ch" # the base hostname & protocol for your site
permalink: /:categories/:title/

## jekyll excludes
exclude:
  - changelog.md
  - '*.*~'
  - '*.xcf'
  - '*.blend*'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
## SEO
geo: 
  timezone: "Europe/Sweden"
  lat: '59.191207'
  long: '17.628346'
  region: 'AB'
  town: 'Södertälje'
  country: 'Sweden'
  postalcode: '15136'

banner:   /images/setto-logo.svg
banner-vert: /images/setto_logo.svg
icon:   /images/setto-logoicon.svg
logo:   /images/setto-logo.svg
logo-footer: /images/setto-logo-dark.svg

# mediaurl: /assets/albums

publisher:
  name: Set Hallström
  domain: set.hallstrom.ch
  mail: set+website@hallstrom.ch
social:
  name: Set Hallstrom
  links:
    - https://www.instagram.com/sethybwoy/
    - http://www.twitter.com/heptazoid
    - https://www.linkedin.com/in/set-hallstrom/   
timezone: Europe/Stockholm

## Matomo
matomo_site_id: '7'
matomo_container: 'DInUucrz'
# defaults
categories:
  - ramblings


collections:
  photos:
    output: false
    _hide_content: true
    sort_by: date
  authors:
    output: false

sass:
  sass_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      lang: en  
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: en
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: en
      permalink: /:title/
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"  
        video_path:
          uploads_dir: "/videos"
  -
    scope:
      path:            "*.pdf"
    values:
      sitemap:         false
  -
    scope:
      path: ""
      type: "photos"
    values:
      layout: "default"
      _options:
        image:
          width: 1280
          height: 720
          resize_style: "contain"
          uploads_dir: "photos"
# ---------
# Translate
lang: en

## Colors

bg:           '#0C0F0A'
fg:           '#FFFFFF'


### PWA
# plugins:
#   - jekyll-pwa-plugin

# pwa:
#   enabled: false # Optional
#   sw_src_filepath: service-worker.js # Optional
#   sw_dest_filename: service-worker.js # Optional
#   dest_js_directory: assets/js # Required
#   precache_recent_posts_num: 5 # Optional
#   precache_glob_directory: / # Optional
#   precache_glob_patterns: # Optional
#     - "assets/{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff,png,jpg,jpeg}"
# #    - "videos/*{mp4,webm}"
#     - "images/**/*.{svg}"
#     - "images/posts/*.{jpg,jpeg,png}"
#     - "images/pages/*.{jpg,jpeg,png}"
# #    - "assets/albums/**/*.{mp3,jpeg}"
#     - index.html
#   precache_glob_ignores: # Optional
#     - sw-register.js
