permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "*.*~", "color_chart.txt", Gemfile, Gemfile.lock]
highlighter: pygments

title : 'Set Hallstrom'
tagline: 'SuperSet'
banner: '/assets/img/basspistol_est_2010_square_bluegreen.jpg'
mblabel: '0f83baf3-4f44-44db-9e30-d5c05d7b77b9'

social_ids: [insta, twitter, facebook, soundcloud, tumblr, archive, mastodon]
social:
  insta: 'https://www.instagram.com/basspistol'
  twitter: 'https://twitter.com/bpist'
  facebook: 'https://www.facebook.com/basspistolQC'
  soundcloud: 'https://soundcloud.com/basspistol'
  tumblr: 'https://basspistol.tumblr.com'
  archive: 'https://archive.org/details/basspistol'
  mastodon: 'https://mastodon.art/@basspistol'

production_url : https://set.hallstrom.ch
baseurl : '/'

# excerpt_separator: '<!--more-->'
pagination:
  enabled: true

