# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Set Hallström'
email: set@hallstrom.ch 
phone: '+46708134377'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://set.hallstrom.ch" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: 'sethybwoy'

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: >- # this means to ignore newlines until "baseurl:"
  'The Digital CV of Set Hallstrom, a multi-disciplanry Artist, a Free Software
  advocate and Community Manager.'
author:
  name: Set Hallstrom
  email: set@hallstrom.ch 
  twitter: # twitter username without the @ symbol
social:
  name: Set Hallstrom
  links:
    - https://www.instagram.com/sethybwoy/
    - http://www.twitter.com/heptazoid
    - https://www.linkedin.com/in/set-hallstrom/   
lang: sv_SE
timezone: Europe/Stockholm

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Plugin settings:

# Site Variables:

# # collection
collections:
  images:
    output: false
    _hide_content: true


# # defaults

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "*.*~", "color_chart.txt", Gemfile, Gemfile.lock]
permalink: /:categories/:year/:month/:day/:title/



defaults:
  -
    scope:
      path:            "*.pdf"
    values:
      sitemap:         false
  -
    scope:
      path: ""
      type: "images"
    values:
      layout: "default"
      _options:
        image:
          width: 1024
          height: 720
          resize_style: "cover"
          uploads_dir: "photos"
